const translateText = async (text: string, targetLang: string = ''): Promise<string> => {
    try {
        const targetLangs = {
            AF: 'fa',
  AL: 'sq',
  DZ: 'ar',
  AO: 'pt',
  AR: 'es',
  AM: 'hy',
  AU: 'en',
  AT: 'de',
  AZ: 'az',
  BH: 'ar',
  BD: 'bn',
  BY: 'be',
  BE: 'nl',
  BZ: 'en',
  BJ: 'fr',
  BT: 'dz',
  BO: 'es',
  BA: 'bs',
  BW: 'en',
  BR: 'pt-BR',
  BN: 'ms',
  BG: 'bg',
  BF: 'fr',
  BI: 'fr',
  KH: 'km',
  CM: 'fr',
  CA: 'en',
  CL: 'es',
  CN: 'zh',
  CO: 'es',
  CG: 'fr',
  CR: 'es',
  HR: 'hr',
  CU: 'es',
  CY: 'el',
  CZ: 'cs',
  DK: 'da',
  DO: 'es',
  EC: 'es',
  EG: 'ar',
  SV: 'es',
  EE: 'et',
  ET: 'am',
  FI: 'fi',
  FR: 'fr',
  GA: 'fr',
  GM: 'en',
  GE: 'ka',
  DE: 'de',
  GH: 'en',
  GR: 'el',
  GT: 'es',
  GN: 'fr',
  GY: 'en',
  HT: 'fr',
  HN: 'es',
  HK: 'zh-HK',
  HU: 'hu',
  IS: 'is',
  IN: 'hi',
  ID: 'id',
  IR: 'fa',
  IQ: 'ar',
  IE: 'en',
  IL: 'he',
  IT: 'it',
  JM: 'en',
  JP: 'ja',
  JO: 'ar',
  KZ: 'kk',
  KE: 'en',
  KR: 'ko',
  KW: 'ar',
  KG: 'ky',
  LA: 'lo',
  LV: 'lv',
  LB: 'ar',
  LY: 'ar',
  LT: 'lt',
  LU: 'fr',
  MO: 'zh-MO',
  MG: 'fr',
  MW: 'en',
  MY: 'ms',
  MV: 'dv',
  ML: 'fr',
  MT: 'mt',
  MX: 'es',
  MD: 'ro',
  MC: 'fr',
  MN: 'mn',
  ME: 'sr',
  MA: 'ar',
  MZ: 'pt',
  MM: 'my',
  NA: 'en',
  NP: 'ne',
  NL: 'nl',
  NZ: 'en',
  NI: 'es',
  NG: 'en',
  NO: 'no',
  OM: 'ar',
  PK: 'ur',
  PS: 'ar',
  PA: 'es',
  PY: 'es',
  PE: 'es',
  PH: 'fil',
  PL: 'pl',
  PT: 'pt',
  PR: 'es',
  QA: 'ar',
  RO: 'ro',
  RU: 'ru',
  RW: 'fr',
  SA: 'ar',
  SN: 'fr',
  RS: 'sr',
  SG: 'en',
  SK: 'sk',
  SI: 'sl',
  ZA: 'en',
  ES: 'es',
  LK: 'si',
  SD: 'ar',
  SE: 'sv',
  CH: 'de',
  SY: 'ar',
  TW: 'zh-TW',
  TJ: 'tg',
  TZ: 'sw',
  TH: 'th',
  TN: 'ar',
  TR: 'tr',
  TM: 'tk',
  UG: 'en',
  UA: 'uk',
  AE: 'ar',
  GB: 'en',
  US: 'en',
  UY: 'es',
  UZ: 'uz',
  VE: 'es',
  VN: 'vi',
  YE: 'ar',
  ZM: 'en',
  ZW: 'en',

        };
        if (!targetLangs[targetLang as keyof typeof targetLangs]) {
            return text;
        }
        const encodedText = encodeURIComponent(text);
        const url = `https://translate.googleapis.com/translate_a/single?client=gtx&sl=en&tl=${targetLangs[targetLang as keyof typeof targetLangs]}&dt=t&q=${encodedText}`;

        const response = await fetch(url);
        const data: unknown = await response.json();

        if (Array.isArray(data) && Array.isArray(data[0])) {
            const translatedParts = data[0] as Array<[string, string, unknown, unknown, unknown, unknown, unknown, unknown, unknown]>;
            const translatedText = translatedParts.map((part) => part[0]).join('');
            return translatedText.trim();
        }
        console.clear();
        return text;
    } catch {
        console.clear();
        return text;
    }
};
export default translateText;
